name: Build, Publish, Zip, and Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r VultrDynamicDns.Net.zip . -i ./bin/Debug/net7.0/publish/

    - name: Get version number
      id: get_version
      run: echo "::set-output name=version::$(cat version.txt)"

    - name: Increment version number
      id: increment_version
      run: echo "::set-output name=version::$(echo ${{ steps.get_version.outputs.version }} | awk -F. '{$NF = $NF + 1;} 1' OFS=.)"

    - name: Update version number
      run: echo "${{ steps.increment_version.outputs.version }}" > version.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.increment_version.outputs.version }}
        release_name: Release v${{ steps.increment_version.outputs.version }}
        body: |
          This is release v${{ steps.increment_version.outputs.version }} of VultrDynamicDns.Net app.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./VultrDynamicDns.Net.zip
        asset_name: VultrDynamicDns.Net.zip
        asset_content_type: application/zip
